### ISSUE TITLE
 Add COSC Team 2017-18 and 2018-19 Details to the Website

### ISSUE THREAD

**Issue by vihar** [cbitosc/cbitosc.github.io#33] opened 2020-03-13 18:51 UTC
Hello Team COSC, 

It is very unfortunate that the founding team(COSC16-17) and the successive team (COSC17-18) were not added to the website. Do take some time and update them on the website. Find the details below, 

Team COSC 2017-18
Vihar Kurama (President)
Anjana Bytha (Vice-President)
Dileep Matha (Secretary)
Harsha Vardhan Rao (Joint Secretary)
Revannth Vedala (Joint Secretary)
Vineeth K (Joint Secretary)
Himanshu K(Joint Secretary)

Team COSC 2016-17
Shekar Kardela (President)
Kalyan Jitendra PJ(Vice President)
Pranith Kumar Raparthi (Secretary) 
Dasarada Ram Reddy Mudiam (Joint Secretary)
G Jeevan (Joint Secretary)

CC: @sekharkaredla @RohithSrk @Rakshita-Yalamanchili @revannth @Krishnaveni004 @r0mflip @pjk23 @harshatech 

Many Thanks, 
Vihar Kurama.

**Comment by notlmn** [comment] 2020-03-22 16:13
Hey @vihar, this change is already being tracked by #10. Lets continue the discussion over there.

Duplicate of #10.

**Closed by notlmn** 2020-03-22 16:13 UTC
